SELECT *
FROM (SELECT ShotDist.PLAYER_NAME,
			 ShotDist.ACTION_TYPE,
			 ROUND(ShotDist.NUM_SHOTS*100/TotalShots.TOTAL_SHOTS, 4) AS PERCENT_OF_SHOTS
	  FROM (SELECT PLAYER_NAME,
				   COUNT(*) AS TOTAL_SHOTS
			FROM shotdata
			GROUP BY PLAYER_NAME) AS TotalShots INNER JOIN
		   (SELECT shotdata.PLAYER_NAME,
				   CASE WHEN UPPER(RIGHT(shotdata.ACTION_TYPE, CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE), CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE)) + 1) - 1)) = ''
						THEN UPPER(shotdata.ACTION_TYPE)
						ELSE UPPER(RIGHT(shotdata.ACTION_TYPE, CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE), CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE)) + 1) - 1))
				   END AS ACTION_TYPE,
				   COUNT(*) AS NUM_SHOTS
			FROM (SELECT PLAYER_NAME
				  FROM shotdata
				  WHERE SHOT_TYPE = '3PT Field Goal'
				  GROUP BY PLAYER_NAME
				  ORDER BY COUNT(*) DESC
				  LIMIT 10) AS 3ptPlayers INNER JOIN
				 shotdata ON 3ptPlayers.PLAYER_NAME = shotdata.PLAYER_NAME
			GROUP BY shotdata.PLAYER_NAME, CASE WHEN UPPER(RIGHT(shotdata.ACTION_TYPE, CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE), CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE)) + 1) - 1)) = ''
												THEN UPPER(shotdata.ACTION_TYPE)
												ELSE UPPER(RIGHT(shotdata.ACTION_TYPE, CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE), CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE)) + 1) - 1))
										   END
			ORDER BY shotdata.PLAYER_NAME, CASE WHEN UPPER(RIGHT(shotdata.ACTION_TYPE, CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE), CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE)) + 1) - 1)) = ''
												THEN UPPER(shotdata.ACTION_TYPE)
												ELSE UPPER(RIGHT(shotdata.ACTION_TYPE, CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE), CHARINDEX(' ', REVERSE(shotdata.ACTION_TYPE)) + 1) - 1))
										   END) AS ShotDist ON TotalShots.PLAYER_NAME = ShotDist.PLAYER_NAME 
	  ORDER BY ShotDist.PLAYER_NAME, ShotDist.ACTION_TYPE)
PIVOT (MAX(PERCENT_OF_SHOTS)
	   FOR ACTION_TYPE IN ('BANK SHOT', 'DUNK SHOT', 'FADEAWAY SHOT', 'HOOK SHOT', 'JUMP SHOT', 'LAYUP SHOT', 'NO SHOT', 'TIP SHOT'))